Fix build in GCC 7
The following error is emitted by gcc 7.3:

include/internal/catch_tostring.cpp:217:21: error: comparison is always true due to limited range of data type [-Werror=type-limits]
|      } else if ('\0' <= value && value < ' ') {
|                 ~~~~~^~~~~~~~
| cc1plus: all warnings being treated as errors

We can drop the first part of the if since '\0' == 0 and it will always
be <= than value of char (which is unsigned by default).

Signed-off-by: Bartosz Golaszewski <bgolaszewski@baylibre.com>