catch_reusable_string_stream.hpp: Ignore warning on LLVM 23
Compiling with LLVM 23.1.2 gives the following compile error:

/usr/bin/clang++-23  -I/home/thomas/devel/Catch2/tests/SelfTest -I/home/thomas/devel/Catch2/src/catch2/.. -I/home/thomas/devel/Catch2/build/generated-includes -Wabsolute-value -Wall -Wcall-to-pure-virtual-from-ctor-dtor -Wcast-align -Wdangling -Wdeprecated -Wdeprecated-register -Wexceptions -Wexit-time-destructors -Wextra -Wextra-semi -Wfloat-equal -Wglobal-constructors -Winit-self -Wmisleading-indentation -Wmismatched-new-delete -Wmismatched-return-types -Wmismatched-tags -Wmissing-braces -Wmissing-declarations -Wmissing-noreturn -Wmissing-prototypes -Wmissing-variable-declarations -Wnon-virtual-dtor -Wnull-dereference -Wold-style-cast -Woverloaded-virtual -Wparentheses -Wpedantic -Wredundant-decls -Wreorder -Wreturn-std-move -Wshadow -Wstrict-aliasing -Wsuggest-destructor-override -Wsuggest-override -Wundef -Wuninitialized -Wunneeded-internal-declaration -Wunreachable-code-aggressive -Wunused -Wunused-function -Wunused-parameter -Wvla -Wweak-vtables -Werror -Wno-missing-noreturn -MD -MT tests/CMakeFiles/SelfTest.dir/SelfTest/UsageTests/Compilation.tests.cpp.o -MF tests/CMakeFiles/SelfTest.dir/SelfTest/UsageTests/Compilation.tests.cpp.o.d -o tests/CMakeFiles/SelfTest.dir/SelfTest/UsageTests/Compilation.tests.cpp.o -c /home/thomas/devel/Catch2/tests/SelfTest/UsageTests/Compilation.tests.cpp
In file included from /home/thomas/devel/Catch2/tests/SelfTest/UsageTests/Compilation.tests.cpp:37:
In file included from /home/thomas/devel/Catch2/src/catch2/../catch2/catch_test_macros.hpp:11:
In file included from /home/thomas/devel/Catch2/src/catch2/../catch2/internal/catch_test_macro_impl.hpp:12:
In file included from /home/thomas/devel/Catch2/src/catch2/../catch2/internal/catch_assertion_handler.hpp:12:
In file included from /home/thomas/devel/Catch2/src/catch2/../catch2/internal/catch_decomposer.hpp:11:
In file included from /home/thomas/devel/Catch2/src/catch2/../catch2/catch_tostring.hpp:19:
/home/thomas/devel/Catch2/src/catch2/../catch2/internal/catch_reusable_string_stream.hpp:46:23: error: address of function 'value' will always evaluate to 'true' [-Werror,-Wpointer-bool-conversion]
   46 |             *m_oss << value;
      |                    ~~ ^~~~~
/home/thomas/devel/Catch2/src/catch2/../catch2/catch_tostring.hpp:121:21: note: in instantiation of function template specialization 'Catch::ReusableStringStream::operator<<<void (void *)>' requested here
  121 |                 rss.operator<<(value);
      |                     ^
/home/thomas/devel/Catch2/src/catch2/../catch2/catch_tostring.hpp:147:68: note: in instantiation of function template specialization 'Catch::StringMaker<void (void *)>::convert<void (void *)>' requested here
  147 |                     std::remove_cv_t<std::remove_reference_t<T>>>::convert( e );
      |                                                                    ^
/home/thomas/devel/Catch2/src/catch2/../catch2/internal/catch_decomposer.hpp:203:42: note: in instantiation of function template specialization 'Catch::Detail::stringify<void (void *)>' requested here
  203 |                     ( os, Catch::Detail::stringify( m_lhs ), m_op, Catch::Detail::stringify( m_rhs ) );
      |                                          ^
/home/thomas/devel/Catch2/src/catch2/../catch2/internal/catch_decomposer.hpp:207:19: note: in instantiation of member function 'Catch::BinaryExpr<void (&)(void *), void (*&)(void *)>::streamReconstructedExpression' requested here
  207 |         constexpr BinaryExpr( bool comparisonResult, LhsT lhs, StringRef op, RhsT rhs )
      |                   ^
1 error generated.

Following the existing pattern we ignore the warning, all tests are
passing.